# Generated by Django 3.0.3 on 2020-03-29 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('patient_sex', models.IntegerField()),
                ('patient_phone', models.CharField(max_length=100)),
                ('prescription_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=100)),
                ('schedule_is_morning', models.IntegerField()),
                ('schedule_is_after_noon', models.IntegerField()),
                ('schedule_is_night', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('duration_type', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_app.Medicine')),
                ('prescription_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription_app.PrescriptionPatient')),
            ],
        ),
    ]
